name: Build Openfirmware

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev git bzip2 python3 python3-pip unzip curl wget file rsync

      - name: Update & Feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Download source
        run: make download -j$(nproc)

      - name: Compile firmware
        run: make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@main
        with:
          name: Firmware
          path: bin/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@main
        with:
          name: Firmware
          path: ./bin

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: ./bin/**/*.bin
